# GCP Settings
api_version: 1
skip_files:
  - ^(.*/)?.*\.py[co]$

# Runtime
runtime: python27
threadsafe: yes

# URLs
handlers:

  # Favicon
  - url: /favicon\.ico
    static_files: static/img/favicon.ico
    upload: bp_content/themes/default/static/favicon.ico
    secure: always

  # Main URLs module
  - url: /.*
    script: main.app
    secure: always

# Third Party Libraries
libraries:
  - name: lxml
    version: "2.3"
